var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};var tvpcv={apiKey:"AIzaSyA2UrVcfcR3_co-0SRvggAfritNB832t-4",authDomain:"send-mail-news.firebaseapp.com",projectId:"send-mail-news",storageBucket:"send-mail-news.appspot.com",messagingSenderId:"735458348101",appId:"1:735458348101:web:9448e2b6fd09b61efee72c"};
firebase.initializeApp(tvpcv);var db=firebase.firestore();function isPostPage(){return document.body.classList.contains("item-view")}function getAds(){return new Promise(function(a,c){db.collection("anunciantes").get().then(function(d){return d.docs.map(function(b){return b.data()})}).then(function(d){return a(d)})["catch"](function(d){return c(d)})})}
function filterAds(a){var c=isPostPage(),d={adsAnchor:[],adsHeader:[],adsMain:[],adsSideBar:[],adsSquares:[],adsFooter:[],adsFloating:[]};a.forEach(function(b){var e=c&&b.pages.includes("post"),f=!c&&b.pages.includes("home");if(e||f)b.local.includes("anchor")&&new Date<=new Date(b.validity)&&d.adsAnchor.push(b),b.local.includes("header")&&new Date<=new Date(b.validity)&&d.adsHeader.push(b),b.local.includes("main")&&new Date<=new Date(b.validity)&&d.adsMain.push(b),b.local.includes("sidebar")&&new Date<=
new Date(b.validity)&&d.adsSideBar.push(b),b.local.includes("squares")&&new Date<=new Date(b.validity)&&d.adsSquares.push(b),b.local.includes("footer")&&new Date<=new Date(b.validity)&&d.adsFooter.push(b),b.local.includes("floating")&&new Date<=new Date(b.validity)&&d.adsFloating.push(b)});return d}
function displayAds(a) {
    var c = document.querySelector(".anchor-ads"), d = document.querySelector(".header-ads"), b = document.querySelectorAll(".main-ads"), e = document.querySelector(".sidebar-ads"), f = document.querySelector(".square-ads"), g = document.querySelector(".footer-ads"), k = document.querySelector(".floating-ads"); adsOneAtATime(c, a.adsAnchor); adsMultipleAtATime(d,a.adsHeader, 4);adsMultipleAtATime(e,a.adsSideBar,5);b.forEach(function(h){return adsOneAtATime(h,a.adsMain)});adsMultipleAtATime(f,a.adsSquares,
6);adsOneAtATime(g,a.adsFooter);adsOneAtATime(k,a.adsFloating)}
function adsOneAtATime(a,c){if(1===c.length){var d=document.createElement("div");d.classList.add("ad");d.id=c[0].id;var b=document.createElement("a");b.href=c[0].link;b.target="_blank";var e=document.createElement("img");e.src=c[0].photoURL;e.alt="Banner do an\u00fancio "+c[0].name;b.appendChild(e);d.appendChild(b);a.appendChild(d)}else if(1<c.length){var f=function(){a.querySelectorAll(".ad").forEach(function(l){return l.remove()});var k=document.createElement("div");k.classList.add("ad");k.id=c[g].id;
var h=document.createElement("a");h.href=c[g].link;h.target="_blank";var m=document.createElement("img");m.src=c[g].photoURL;m.alt="Banner do an\u00fancio "+c[g].name;h.appendChild(m);k.appendChild(h);a.appendChild(k);g=Math.floor(Math.random()*(c.length-0))},g=Math.floor(Math.random()*(c.length-0));f();setInterval(function(){f()},5E3)}}
function adsMultipleAtATime(a,c,d){1<=c.length&&c.length<=d?c.forEach(function(b){var e=document.createElement("div");e.classList.add("ad");e.id=b.id;var f=document.createElement("a");f.href=b.link;f.target="_blank";var g=document.createElement("img");g.src=b.photoURL;g.alt="Banner do an\u00fancio "+b.name;f.appendChild(g);e.appendChild(f);a.appendChild(e)}):1<c.length&c.length>d&&(refreshAdsMultiple(a,c,d),setInterval(function(){return refreshAdsMultiple(a,c,d)},5E3))}
function refreshAdsMultiple(a,c,d){d=generateRandomArray(0,c.length-1,d);a.querySelectorAll(".ad").forEach(function(b){return b.remove()});d.forEach(function(b){b=c[b];var e=document.createElement("div");e.classList.add("ad");e.id=b.id;var f=document.createElement("a");f.href=b.link;f.target="_blank";var g=document.createElement("img");g.src=b.photoURL;g.alt="Banner do an\u00fancio "+b.name;f.appendChild(g);e.appendChild(f);a.appendChild(e)})}
function generateRandomArray(a,c,d,b){b=void 0===b?1:b;for(var e=new Set;e.size<d;){for(var f=Math.floor(Math.random()*(c-a+1))+a,g=!0,k=$jscomp.makeIterator(e),h=k.next();!h.done;h=k.next())if(Math.abs(f-h.value)<b){g=!1;break}g&&e.add(f)}return Array.from(e)}
function initRenderAds(){if(isPostPage()){var a=document.querySelectorAll(".post-body br"),c=null;4>=a.length?c=1:4<a.length&&8>=a.length?c=2:8<a.length&&12>=a.length?c=3:12<a.length&&(c=4);c=generateRandomArray(0,a.length-3,c,3);for(var d=0;d<c.length;d++)a[c[d]].insertAdjacentHTML("afterend",'<div class="main-ads ads-region"></div>')}else for(a=document.querySelectorAll(".post-outer-container"),c=0;c<a.length;c++)0===(c+2)%3&&a[c].insertAdjacentHTML("afterend",'<div class="main-ads ads-region"></div>');
getAds().then(function(b){return filterAds(b)}).then(function(b){return displayAds(b)}).then(function(){return initStatistics()})}
function initStatistics(){function a(b,e){db.collection("statistics").doc(b).get().then(function(f){function g(k,h){var m=formatDateString((new Date).toLocaleDateString());db.collection("statistics/"+k+"/byDay").doc(m).get().then(function(l){l.exists?(l=l.data(),l[h]+=1,db.collection("statistics/"+k+"/byDay").doc(m).update(l)["catch"](function(n){return console.error(n)})):(l={clicks:0,views:0,prints:0},l[h]+=1,db.collection("statistics/"+k+"/byDay").doc(m).set(l)["catch"](function(n){return console.error(n)}))})}
f.exists?(f=f.data(),f[e]+=1,db.collection("statistics").doc(b).update(f).then(function(){return g(b,e)})):(f={clicks:0,views:0,prints:0},f[e]+=1,db.collection("statistics").doc(b).set(f).then(function(){return g(b,e)}))})}var c=document.querySelectorAll(".ad"),d=new IntersectionObserver(function(b){b.forEach(function(e){var f=e.target.id;e.isIntersecting?setTimeout(function(){e.isIntersecting&&a(f,"views")},2E3):clearTimeout()})});c.forEach(function(b){var e=b.id;d.observe(b);a(e,"prints");b.onclick=
function(f){return a(e,"clicks")}})}function formatDateString(a){var c=parseInt(a.split("/")[0]),d=parseInt(a.split("/")[1]);a=parseInt(a.split("/")[2]);return d+"-"+c+"-"+a}initRenderAds();document.querySelector(".floating-ads .close").onclick=function(){var a=document.querySelector(".floating-ads");a.style.transform="scale(0)";setTimeout(function(){return a.style.transform="scale(1)"},15E3)};
document.querySelector(".anchor-ads .show-hide").onclick=function(){var a=document.querySelector(".anchor-ads");a.classList.toggle("active");setTimeout(function(){return a.classList.add("active")},15E3)};
